{
 "title": "Router",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   { "name": "rate_interval", "query": "6m" },
   { "name": "device_type", "query": "Gateway" },
   {
    "name": "port_ID",
    "query": {
     "query": "label_values(port_info{deviceType=\"$device_type\"},portID)"
    }
   },
   {
    "name": "device_name",
    "label": "Controler Name",
    "query": {
     "query": "label_values(device_info{deviceType=\"$device_type\"},deviceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * $__range",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN LoadBalancing Active Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_upstream_state{deviceType=\"$device_type\", device_name=\"$device_name\"}\n* on (macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$device_type\", device_name=\"$device_name\", portMode=\"WAN\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portName}}"
    }
   ]
  },
  {
   "title": "Used Gateway over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "group(\n    port_upstream_state{deviceType=\"$device_type\", device_name=\"$device_name\"}\n    * on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\", device_name=\"$device_name\", portMode=\"WAN\"} == 1) by (macAddress, portID, portName, portMode)\n    ) by (portName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port $port_ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "port_ID",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_speed{deviceType=\"$device_type\", device_name=\"$device_name\", portID=\"$port_ID\"}\n  * on(macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$device_type\", device_name=\"$device_name\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "port_internet_loss{deviceType=\"$device_type\", device_name=\"$device_name\"}\n* on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\", device_name=\"$device_name\", portMode=\"WAN\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portName}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "port_internet_latency{deviceType=\"$device_type\", device_name=\"$device_name\"}\n* on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\", device_name=\"$device_name\", portMode=\"WAN\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portName}}"
    }
   ]
  },
  {
   "title": "Router Port TX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n  * on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\", portMode!=\"\"} == 1) by (macAddress, portID, portName, portMode)\n) * 8",
     "legendFormat": "port: {{portID}} - {{portMode}}"
    }
   ]
  },
  {
   "title": "Router Port RX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n  * on (macAddress, portID) group_left(portName, portMode)\n  max(port_info{deviceType=\"$device_type\", device_name=\"$device_name\", portMode!=\"\"} == 1) by (macAddress, portID, portName, portMode)\n) * 8",
     "legendFormat": "port: {{portID}} - {{portMode}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    },
    {
     "expr": "memory_usage{deviceType=\"Gateway\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(\n    temperature{deviceType=\"$device_type\", device_name=\"$device_name\"}\n    * on(macAddress) group_left(deviceName)\n    device_info{deviceType=\"$device_type\", device_name=\"$device_name\"}\n)",
     "legendFormat": "{{deviceName}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8",
     "legendFormat": "Router Throughput"
    }
   ]
  },
  {
   "title": "Port Config",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "port_info{deviceType=\"$device_type\", device_name=\"$device_name\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\", device_name=\"$device_name\"}) by (macAddress, deviceName)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}