{
 "title": "Switch",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   { "name": "rate_interval", "query": "6m" },
   { "name": "deviceType", "query": "Switch" },
   {
    "name": "port_ID",
    "query": {
     "query": "label_values(port_info{deviceType=\"$deviceType\"},portID)"
    }
   },
   {
    "name": "max_port_speed",
    "query": {
     "query": "query_result(scalar(max(max_over_time(port_speed{deviceType=\"$deviceType\"}[$__range]))))"
    }
   },
   {
    "name": "deviceName",
    "label": "Controler Name",
    "query": {
     "query": "label_values(device_info{deviceType=\"$deviceType\"},deviceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval]))\n) * $__range",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval]))\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    count(port_speed{deviceType=\"$deviceType\", deviceName=\"$deviceName\"} > 0) /\n    count(port_speed{deviceType=\"$deviceType\", deviceName=\"$deviceName\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$deviceName",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "deviceName",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_speed{deviceType=\"$deviceType\"}\n  * on(macAddress, portID) group_left(portName, portMode)\nport_info{deviceType=\"$deviceType\"}\n  * on(macAddress) group_left(deviceName)\ndevice_info{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch port TX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval]))\n) * 8\n* on (macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$deviceType\", deviceName=\"$deviceName\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Switch port RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_rx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval]))\n) * 8\n* on (macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$deviceType\", deviceName=\"$deviceName\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$deviceType\", deviceName=\"$deviceName\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (CPU)"
    },
    {
     "expr": "memory_usage{deviceType=\"$deviceType\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$deviceType\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (RAM)"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$deviceType\", deviceName=\"$deviceName\"}[$rate_interval]))\n) * 8",
     "legendFormat": "Switch Throughput"
    }
   ]
  }
 ]
}